name: gEssentialsGUI
version: 1.0.0-BETA
author: goncalviz
main: br.goncalviz.essentialsgui.Main
commands:
  essentials:
    aliases: [utils, eg]
    description: Comando para abrir o menu de utilidades